project:
  type: website
  output-dir: C:/Users/ra204.stu/Desktop/GEM 510/Week8/E-Portfolio/Who Rama is.pdf

website:
  title: "Rama Arade"
  navbar:
    left:
      - href: index.qmd
        text: Home
        text: Resume
      - href: C:/Users/ra204.stu/Desktop/GEM 510/Week8/E-Portfolio/Rama Arade's Resume  .docx.pdf
      - href: publications.qmd
        text: Publications
      - text: GifHub
        href: https://github.com/ramaarade
        text: email
        href: mail to:ramaarade@gmail.com


format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

